---
title: "Owen_finalproj"
output: html_document
date: "2024-01-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Packages

```{r}
library(terra)
library(ggplot2)
library(dplyr)
library(sf)
library(tidyterra)
library(sp)
library(ggspatial)
library(exactextractr)
library(igraph)
library(networkD3)
library(tidyr)
library(ggalluvial)
library(ggrepel)
library(stringr)
```

# Data Cleaning

```{r}
OBAraw<-read.csv("Akiyama_ProjectData/OBA_2018-2023.csv")
OBA<-subset(OBAraw, Dec..Long. != "" & Dec..Lat. != "")
OBA<-subset(OBA, State=="OR" | State== "Oregon" | State== "Oregon ")
OBA<-subset(OBA, Genus!="" & Associated.plant...genus..species!= "" & Associated.plant...genus..species!= "NA")
OBA<-unite(OBA, col="gspecies", c('Genus', 'Species'), sep=' ', remove=FALSE)
OBA$plantresolution<-str_detect(OBA$Associated.plant...genus..species, pattern="\\w\\s\\w")




```

# Shapefile Setup:

```{r}
OBA_sf <- st_as_sf(OBA, coords = c("Dec..Long.", "Dec..Lat."),
                                  crs = 4326)
or <- map_data( "state","oregon") %>% 
  dplyr::select(lon = long, lat, group, id = subregion)

or_poly <- or %>%
  st_as_sf(coords=c("lon","lat"), crs=4326)%>%
  summarise(geometry = st_combine(geometry)) %>%
  st_cast("POLYGON")

OBA_crop<-st_filter(OBA_sf,or_poly)

#possibly unecessary
#or_sf<-st_as_sf(or, coords=c("lon","lat"),, group=TRUE, crs=4326)

ggplot()+
  geom_polygon(data=or, aes(x=lon,y=lat, group=group)) +
  geom_sf(data=OBA_crop, color='yellow') 
```

# Raster Setup

```{r}
vegcover<-rast("Akiyama_ProjectData/gaplf2011lc_v30_or/gaplf2011lc_v30_or.tif")
#attributes
vegcover_at<-read.delim("Akiyama_ProjectData/gaplf2011lc_v30_or/GAP_LANDFIRE_National_Terrestrial_Ecosystems_2011_Attributes.txt")

### get a list of the numbers associated with all the land types in this raster (put this in # because converting to df took 20 min)

#vegcover_df <- as.data.frame(vegcover, xy = TRUE)
#head(vegcover_df)

#unique_vegcover<-unique(vegcover_df$gaplf2011lc_v30_or)
#save(unique_vegcover, file = "unique_vegcover.rda")
load("Akiyama_ProjectData/unique_vegcover.rda")

### get the categorical land types associated with those numbers
landtype<- matrix(0,161,1)
for (n in 1:161) {
  
  landnum<-unique_vegcover[n]
 
  landtype[n,1]<-vegcover_at[which(vegcover_at$Value == landnum),19]
  
}


#associate values with categories within the raster
fromto <- as.matrix(data.frame(from = unique_vegcover , to = landtype))
fromto_df<-as.data.frame(fromto)
fromto_df$from<-as.numeric(fromto_df$from)

levels(vegcover)<-fromto_df

#reproj vegcover
vegcover_reproj<-project(vegcover, crs(OBA_crop))



```

# Raster Graph

```{r}
## Regular R raster plot:

#plot(vegcover,type= "classes",legend=TRUE,plg=list(
#                title = "Terrestrial Ecosystem Type",
#                title.cex = 1, 
#                cex = 0.14), fun=\() lines(or))


##THIS GRAPH LOOKS HORRIBLE
pdf("vegcoverplot3.pdf")
vegcoverplot<-ggplot()+
  geom_spatraster(data=vegcover_reproj) +
  scale_fill_viridis_d(name="Ecosystem \n Types") +
  geom_path(data=or, aes(x=lon,y=lat, group=group)) +
  ggtitle("NatureServe Vegetation Cover in Oregon") +
  annotation_scale(height = unit(3, "cm"),   text_cex = 3) +
  theme(plot.title = element_text(size=70),
        legend.position= "right",
        legend.text = element_text(size=30),
        legend.title = element_text(size=50),
        plot.caption = element_text(size=50),
        plot.caption.position= "plot"
        )
print(vegcoverplot)

ggsave(
  "vegcoverplot3.pdf",
  plot = last_plot(),
  device = NULL,
  path = NULL,
  scale = 1,
  width = 130,
  height = 48,
  units = c("in", "cm", "mm", "px"),
  dpi = 300,
  limitsize = FALSE,
  bg = NULL)


         
```

# Input Coordinates

```{r}
#longitude:
x<--123.285

#latitude:
y<-44.556
```

# What is the Vegetation Type?

```{r}

onecoord<-as.data.frame(matrix(c(y,x),nrow=1,ncol=2)) 
colnames(onecoord)<-c("lat","lon") 
onecoord_sf <- st_as_sf(onecoord, coords = c("lon","lat"), crs = 4326) 
onevegtype<-terra::extract(x=vegcover_reproj, y=onecoord_sf) 
onevegtype<-as.data.frame(onevegtype)[1,2]
OBA_onetype_sf<-OBA_crop[which(vegbee_master$to == onevegtype),] 
OBA_onetype<-as.data.frame(OBA_onetype_sf)

sprintf("This point is within %s vegetation cover",onevegtype)


#a function that doesn't work #toplist <- function(x){ # funclist<-OBA_onetype %>% group_by (x) %>% tally() # funclist<-random[order(funclist$n, decreasing = TRUE),1:2] #return(funclist) }
```

# Get Vegetation Type Info

```{r}
URL<-gsub(" ","+",onevegtype)
URL<-sprintf("https://www.google.com/search?q=%s+site%%3Ahttps%%3A%%2F%%2Fexplorer.natureserve.org",URL)
browseURL(URL)
```

# Statistics & Graphs

## Bee genera of interest

```{r}
genuslist<-OBA_onetype %>% group_by(Genus) %>% tally()
genuslist<-genuslist[order(genuslist$n, decreasing = TRUE),1:2]
genuslist

ggplot(data =genuslist[1:10,], aes(x=reorder(Genus, -n), y=n, fill =Genus)) +
  geom_bar(stat='identity',show.legend = FALSE)+
  ggtitle("Most Common Bee Genera") +
  xlab("") +
  ylab("# of Observations") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        plot.title = element_text(size=10)) +
  scale_color_brewer()



```

## Bee species of interest

```{r}
subset(OBA_onetype, plantresolution == TRUE)

specieslist<-OBA_onetype %>% group_by(gspecies) %>% tally()
specieslist<-specieslist[order(specieslist$n, decreasing = TRUE),1:2]
specieslist[1:25,]

ggplot(data =specieslist[1:25,], aes(x=reorder(gspecies, -n), y=n, fill =gspecies)) +
  geom_bar(stat='identity',show.legend = FALSE)+
  ggtitle("Most Common Bee species") +
  xlab("") +
  ylab("# of Observations") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        plot.title = element_text(size=10)) +
  scale_color_brewer()

```

## Most Abundant Associated Plant Species

```{r}
plantlist<-OBA_onetype %>% group_by(Associated.plant...genus..species) %>% tally()
plantlist<-plantlist[order(plantlist$n, decreasing = TRUE),1:2]

ggplot(data =plantlist[1:25,], aes(x=reorder(Associated.plant...genus..species, -n), y=n, fill =Associated.plant...genus..species)) +
  geom_bar(stat='identity',show.legend = FALSE)+
  ggtitle("Most Common Pollinator Associated Plants") +
  xlab("") +
  ylab("# of Associated Bee Observations") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        plot.title = element_text(size=10)) +
  scale_color_brewer()

```

## Most Diverse Associated Plant Species

```{r}
allplants<-as.data.frame(unique(OBA_onetype$Associated.plant...genus..species))
colnames(allplants)<-"plant"
allplants$uniquebeespecies = NA
for (a in 1:nrow(allplants)) {
    oneplantsubset<-subset(OBA_onetype, Associated.plant...genus..species == allplants[a,1])
    allplants[a,2]<-length(unique(oneplantsubset$gspecies))
}


ggplot(data =allplants[1:25,], aes(x=reorder(plant, -uniquebeespecies), y=uniquebeespecies, fill =plant)) +
  geom_bar(stat='identity',show.legend = FALSE)+
  ggtitle("Plants With Most Pollinator Diversity") +
  xlab("") +
  ylab("# of Unique Associated Bee Species") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        plot.title = element_text(size=10)) +
  scale_color_brewer()

```

## Alluvial Network

```{r}

pdf("greasyplot.pdf")

mybeenetworkplot<-ggplot(data = OBA_onetype,
       aes(axis1 = Associated.plant...genus..species, axis2 = gspecies,)) +
  geom_alluvium(aes(fill = Associated.plant...genus..species),show.legend = FALSE, ) +
  geom_stratum() +
  geom_label(stat = "stratum",
            aes(label = after_stat(stratum))) +
  scale_x_discrete(limits = c("Associated.plant...genus..species", "gspecies"),
                   expand = c(0.15, 0.05)) +
  theme_void()
mybeenetworkplot


  ggsave('mybeenetworkplot.pdf', 
        width = unit(25, 'in'), height = unit(30, 'in'))
```

# 

# Appendix

### Unused igraph network code

```{r}
OBA_net<-subset(OBA_onetype, select= c(gspecies, Associated.plant))
OBA_net<-as.data.frame(OBA_net)
OBA_net<-OBA_net[,1:2]

OBA_netvert<-distinct(gather(OBA_net))
OBA_netvert<-OBA_netvert[,c(2,1)]
OBA_netvert<-OBA_netvert$key ==
  OBA_netvert['key'][OBA_netvert['key'] == 'gspecies']<- 'TRUE'


OBA_netvert$type<-as.logical(ifelse(OBA_netvert$key == "gspecies","TRUE","FALSE"))
 
OBA_netgraph <- graph_from_data_frame(OBA_net, directed=FALSE, vertices=OBA_netvert)

plot(OBA_netgraph, layout=layout.bipartite, weighted=TRUE, vertex.size=0.5,
     vertex.label.cex=0.1, hgap=5000, vgap= 20)


bipartite_projection(OBA_netgraph)

vegcover_greasewood<- vegcover_reproj =="Inter-Mountain Basins Greasewood Flat"
plot(vegcover_greasewood)
```
